LSP Notebooks experiment is disabled -- not using Pylance
> conda info --json
> ~/.pyenv/versions/3.8.13/bin/python /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/pythonFiles/get_output_via_markers.py /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/pythonFiles/interpreterInfo.py
> /bin/python2 /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/pythonFiles/get_output_via_markers.py /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/pythonFiles/interpreterInfo.py
> /bin/python3 /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/pythonFiles/get_output_via_markers.py /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/pythonFiles/interpreterInfo.py
> /usr/bin/python2 /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/pythonFiles/get_output_via_markers.py /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/pythonFiles/interpreterInfo.py
> /usr/bin/python3 /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/pythonFiles/get_output_via_markers.py /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/pythonFiles/interpreterInfo.py
Python interpreter path: ~/.pyenv/versions/3.8.13/bin/python
[ERROR 2022-5-29 7:44:58.856]: [
  `Failed to start language server, Class name = u, completed in 67ms, has a falsy return value, Arg 1: <Uri:/workspace/Bot>, Arg 2: {"id":"/home/gitpod/.pyenv/versions/3.8.13/bin/python","sysPrefix":"/home/gitpod/.pyenv/versions/3.8.13","envType":"Pyenv","envName":"3.8.13","envPath":"/home/gitpod/.pyenv/versions/3.8.13","path":"/home/gitpod/.pyenv/versions/3.8.13/bin/python","architecture":3,"sysVersion":"3.8.13 (default, Jun 19 2022, 14:08:28) \\n[GCC 9.4.0]","version":{"raw":"3.8.13","major":3,"minor":8,"patch":13,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.8.13 64-bit ('3.8.13')","detailedDisplayName":"Python 3.8.13 64-bit ('3.8.13': pyenv)"}, Arg 3: {"documentSelector":[{"scheme":"file","language":"python"},{"scheme":"untitled","language":"python"},{"scheme":"vscode-notebook","language":"python"},{"scheme":"vscode-notebook-cell","language":"python"},{"scheme":"vscode-interactive-input","language":"python"}],"workspaceFolder":{"uri":{"$mid":1,"fsPath":"/workspace/Bot","external":"file:///workspace/Bot","path":"/workspace/Bot","scheme":"file"},"name":"Bot","index":0},"synchronize":{"configurationSection":"python"},"outputChannel":{"name":"Python Language Server"},"revealOutputChannelOn":4,"initializationOptions":{"markupKindPreferred":"markdown","completion":{"resolveEagerly":false,"disableSnippets":false},"diagnostics":{"enable":true,"didOpen":true,"didSave":true,"didChange":true},"workspace":{"extraPaths":["/workspace/Bot"],"symbols":{"maxSymbols":0}}},"middleware":{"serviceContainer":{"container":{"options":{"autoBindInjectable":false,"defaultScope":"Transient","skipBaseClassChecks":true},"id":0,"_bindingDictionary":{"_map":{}},"_snapshots":[],"_middleware":null,"parent":null,"_metadataReader":{}}},"lastCaptured":{},"nextWindow":0,"eventCount":0,"workspace":{},"connectedPromise":{"scope":null,"_resolved":false,"_rejected":false,"_promise":{}},"eventName":"JEDI_LANGUAGE_SERVER.REQUEST","notebookAddon":{}}}, Return Value: undefined`,
  [s [Error]: Pending response rejected since connection got disposed
  	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2129991)
  	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181357)
  	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181635)
  	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2336299)
  	at /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181445
  	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
  	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
  	at Z (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2118347)
  	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
  	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
  	at g.fireClose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2140289)
  	at Socket.<anonymous> (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2141845)
  	at Socket.emit (node:events:402:35)
  	at Pipe.<anonymous> (node:net:687:12)] {
    code: -32097,
    data: undefined
  }
]
[ERROR 2022-5-29 7:44:58.858]: [
  'Starting language server, Class name = h, completed in 69ms, has a falsy return value, , Return Value: undefined',
  [s [Error]: Pending response rejected since connection got disposed
  	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2129991)
  	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181357)
  	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181635)
  	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2336299)
  	at /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181445
  	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
  	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
  	at Z (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2118347)
  	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
  	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
  	at g.fireClose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2140289)
  	at Socket.<anonymous> (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2141845)
  	at Socket.emit (node:events:402:35)
  	at Pipe.<anonymous> (node:net:687:12)] {
    code: -32097,
    data: undefined
  }
]
[ERROR 2022-5-29 7:44:58.858]: [
  `Failed to start language server, Class name = h, completed in 70ms, has a falsy return value, Arg 1: <Uri:/workspace/Bot>, Arg 2: {"id":"/home/gitpod/.pyenv/versions/3.8.13/bin/python","sysPrefix":"/home/gitpod/.pyenv/versions/3.8.13","envType":"Pyenv","envName":"3.8.13","envPath":"/home/gitpod/.pyenv/versions/3.8.13","path":"/home/gitpod/.pyenv/versions/3.8.13/bin/python","architecture":3,"sysVersion":"3.8.13 (default, Jun 19 2022, 14:08:28) \\n[GCC 9.4.0]","version":{"raw":"3.8.13","major":3,"minor":8,"patch":13,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.8.13 64-bit ('3.8.13')","detailedDisplayName":"Python 3.8.13 64-bit ('3.8.13': pyenv)"}, Return Value: undefined`,
  [s [Error]: Pending response rejected since connection got disposed
  	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2129991)
  	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181357)
  	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181635)
  	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2336299)
  	at /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181445
  	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
  	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
  	at Z (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2118347)
  	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
  	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
  	at g.fireClose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2140289)
  	at Socket.<anonymous> (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2141845)
  	at Socket.emit (node:events:402:35)
  	at Pipe.<anonymous> (node:net:687:12)] {
    code: -32097,
    data: undefined
  }
]
[ERROR 2022-5-29 7:44:58.858]: [
  'Failed to activate a workspace, Class name = f, completed in 766ms, has a falsy return value, Arg 1: <Uri:/workspace/Bot/main.py>, Return Value: undefined',
  [s [Error]: Pending response rejected since connection got disposed
  	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2129991)
  	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181357)
  	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181635)
  	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2336299)
  	at /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181445
  	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
  	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
  	at Z (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2118347)
  	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
  	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
  	at g.fireClose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2140289)
  	at Socket.<anonymous> (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2141845)
  	at Socket.emit (node:events:402:35)
  	at Pipe.<anonymous> (node:net:687:12)] {
    code: -32097,
    data: undefined
  }
]
[ERROR 2022-5-29 7:44:58.858]: Failure during activation. [s [Error]: Pending response rejected since connection got disposed
	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2129991)
	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181357)
	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181635)
	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2336299)
	at /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181445
	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
	at Z (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2118347)
	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
	at g.fireClose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2140289)
	at Socket.<anonymous> (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2141845)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)] {
  code: -32097,
  data: undefined
}
[ERROR 2022-5-29 7:44:58.858]: sendStartupTelemetry() failed. [s [Error]: Pending response rejected since connection got disposed
	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2129991)
	at Object.dispose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181357)
	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181635)
	at S.handleConnectionClosed (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2336299)
	at /workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2181445
	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
	at Z (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2118347)
	at invoke (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2131704)
	at o.fire (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2132469)
	at g.fireClose (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2140289)
	at Socket.<anonymous> (/workspace/.vscode-remote/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2141845)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)] {
  code: -32097,
  data: undefined
}
